@startuml Admin Login Sequence Diagram 
title Admin Login Sequence Diagram
actor Admin
participant "Server" as Server
participant "Auth Controller" as Auth
database "User Model" as Model

Admin -> Server: POST /api/v1/auth/admin/login
activate Server

Server -> Auth: login(req, res, next)
activate Auth

Auth -> Model: findOne({email}).select('+password')
activate Model

Model --> Auth: Returns admin data
deactivate Model

Auth --> Server: sendTokenResponse(admin,200,res)
deactivate Auth

Server --> Admin: Response with token
deactivate Server
@enduml