@startuml User Register Sequence Diagram  
title User Register Sequence Diagram
actor User
participant "Server" as Server
participant "Auth Controller" as Auth
database "User Model" as Model

User -> Server: POST /api/v1/auth/register
activate Server

Server -> Auth: register(req, res, next)
activate Auth

Auth -> Model: create(req.body)
activate Model

Model --> Auth: Returns created user data
deactivate Model

Auth --> Server: sendTokenResponse(user, 200, res)
deactivate Auth

Server --> User: Response with token
deactivate Server
@enduml