@startuml User Login Sequence Diagram 
title User Login Sequence Diagram
actor User
participant "Server" as Server
participant "Auth Controller" as Auth
database "User Model" as Model

User -> Server: POST /api/v1/auth/login
activate Server

Server -> Auth: login(req, res, next)
activate Auth

Auth -> Model: findOne({email}).select('+password')
activate Model

Model --> Auth: Returns user data
deactivate Model

Auth --> Server: sendTokenResponse(user,200,res)
deactivate Auth

Server --> User: Response with token
deactivate Server
@enduml