@startuml User Get Own Reservations Sequence Diagram
title User Get Own Reservations Sequence Diagram
actor User
participant "Server" as Server
participant "Auth Middleware" as Auth
participant "Reservation Controller" as Controller
database "Reservation Model" as Model

User -> Server: GET /api/v1/reservations
activate Server

Server -> Auth: protect(req, res, next)
activate Auth

Auth --> Server: Returns user data
deactivate Auth

Server -> Controller: getReservations(req, res, next)
activate Controller

Controller -> Model: find({user:req.user.id})
activate Model

Model --> Controller: Returns user's reservations
deactivate Model

Controller --> Server: Returns success response with reservations data
deactivate Controller

Server --> User: Returns success response with reservations data
deactivate Server
@enduml